---
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
cache:
  yarn: true
  directories:
  - node_modules
install:
  - yarn install
script:
  - yarn lint
  - yarn build-and-qa
notifications:
  email:
    on_success: never
    on_failure: change
