---
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn build-and-qa
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
